import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { demos } from "./demos";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="border-b mb-8">
          {/* Scrolls rather than wrapping, so the header stays one line as demos are added. */}
          <ol className="flex gap-4 p-4 overflow-x-auto whitespace-nowrap text-sm">
            <li>
              <Link href="/" className="font-medium hover:underline">
                Home
              </Link>
            </li>
            {demos.map((demo) => (
              <li key={demo.href}>
                <Link
                  href={demo.href}
                  className="text-muted-foreground hover:text-foreground hover:underline"
                >
                  {demo.label}
                </Link>
              </li>
            ))}
          </ol>
        </nav>
        {children}
      </body>
    </html>
  );
}
